src/main/java/com/google/sps/utils/GameUtils.java, src/test/java/com/google/sps/IsValidGameNameTest.java
The isValidGameName helper function checks whether a game name is valid when a new game is created, or when a user joins a game to make sure the game name isn't blank and the user doesn't have two games of the same name. The tests cover new and duplicate names, different capitalization (users can have a game called Game and a game called game), an empty string, and a null user entity.
=> Is valid game name helper

src/main/java/com/google/sps/utils/GameUtils.java, src/test/java/com/google/sps/CreateGameTest.java, src/test/java/com/google/sps/IsValidGameNameTest.java
Create game entity helper function adds gameName, userIds, quizQuestion and timestamp to a new game and stores the game in datastore. The testing covers giving the function a null datastore instance or an empty string.
=> Add create game entity helper function

src/main/java/com/google/sps/servlets/BlobstoreUploadUrlServlet.java, src/main/java/com/google/sps/servlets/ServeImageServlet.java
This function is called on image upload; it creates a url and attaches it to the form so the browser can upload the file directly to blobstore. The serve image servlet obtains a url to serve the blob image.
=> servlet for creating an upload url for plant images

src/main/java/com/google/sps/utils/CookieUtils.java, src/test/java/com/google/sps/CookieUtilsTest.java, src/test/java/com/google/sps/GetCookieGivenNameTest.java
Created a helper function to query a specific cookie given the cookie's name. Wrote tests for this also
=> create helper function to find a specific cookie

src/main/webapp/blobstoreFunctions.js, src/main/webapp/imageUpload.html
fetchBlobstoreUrl allows BlobstoreUploadUrlServlet to attach url to the upload form; image to page gets the url served by serveImageServlet and the correct blobkey from getBlobKeyServlet; createListElement creates the card to put the image on the page. The html inlcudes an upload form and a button that shows the image if there is one.
=> Blobstore javascript and html

src/main/webapp/gameBoard.html, src/main/webapp/gameFunctions.js
The Js function calls on a servlet that checks whether the user has taken the quiz or not. If not the button to take a quiz will show up in the html. If so, the button will not show.
=> edited the game board html and js file

src/main/java/com/google/sps/servlets/joinGameServlet.java
Join game servlet adds a user to a game if they are not already part of the game, given the code for the game
=> Add join game servlet to add a user to a game

src/main/java/com/google/sps/servlets/startGameServlet.java, src/main/java/com/google/sps/utils/GameUtils.java, src/test/java/com/google/sps/GameUtilTest.java
Start game servlet creates a game if a user doesn't already have a game, and adds the user to the game and the game to the user
=> Add start game servlet to create game entity

src/main/java/com/google/sps/utils/UserUtils.java, src/test/java/com/google/sps/UserUtilTest.java
This function adds a specified number of points to the user; the tests cover if the user already has points and if the user doesn't already have points. This also fixes a typo in the sessionIDcookieName variable
=> add function to add points to a user and test the function

src/main/java/com/google/sps/servlets/UserQuizStatusServlet.java
This servlet checks if the current user has taken a quiz. It calls on the helper functions to do this.
=> Usertookquiz

src/main/java/com/google/sps/utils/QuizTimingPropertiesUtils.java, src/test/java/com/google/sps/TimingPropertiesTest.java
I changed the parameters accepted by on the functions and adjusted their respective tests. I also did some renaming
=> Renaming and Rewriting Functions 

src/main/webapp/quiz.html, src/main/webapp/quizFunctions.js
The quiz html page is updated with all the needed tags. The js file has all the fetch functions need to populate the quiz page and select the right users to give points to.
=> quiz page html and js files

src/main/java/com/google/sps/servlets/GameQuizStatusServlet.java, src/main/java/com/google/sps/utils/QuizTimingPropertiesUtils.java
The servlet gets the quiz question. It will get a new question if the old one is outdated.
=> GameQuizStatusServlet

src/main/webapp/gameBoard.html, src/main/webapp/gameFunctions.js
Add js functions to get users of a game from the server and create a list element to list them by score for the leaderboard.
=> Leaderboard html js

src/main/java/com/google/sps/utils/UserUtils.java, src/test/java/com/google/sps/UserUtilTest.java
(Code refactoring) Made a function that takes in all necessary parameters and creates a User Entity. If a user already exists, it just updates the Session ID (code used to be in PopulateUserUtils.java)
=> Add a createUserEntity function to userUtils

src/main/java/com/google/sps/servlets/getUserImagesForQuizPage.java
This servlet loads images for the quiz page if the user is logged in. It does not add the photo of the user who is logged in though
=> Imagesforquizpage

src/main/java/com/google/sps/servlets/populateLeaderboardServlet.java
Gets all users in the game with the userList function and returns the arraylist of user objects.
=> Servlet to get the user objects for the game the current user is playing

src/main/java/com/google/sps/servlets/QuizPoints.java, src/main/java/com/google/sps/servlets/getUserImagesForQuizPage.java
changing the name of variables that caused errors when deployed
=> Renaming Variables

src/main/java/com/google/sps/utils/CookieUtils.java, src/test/java/com/google/sps/CookieUtilsTest.java
Created a function that takes in the current session and the new session Id and returns a cookie.
=> created createSessionIDCookie() fxn (+tests!)

src/main/java/com/google/sps/utils/Game.java, src/test/java/com/google/sps/GameTest.java, src/test/java/com/google/sps/TimingPropertiesTest.java
made a game class and used it in test functions
=> game class

src/main/java/com/google/sps/servlets/populateLeaderboardServlet.java, src/main/java/com/google/sps/utils/User.java
Manually converting (as opposed to using gson) the user objects to json to send to the js so the js doesn't have to deal with entities and entity properties.
=> Send user objects to javascript

src/main/java/com/google/sps/servlets/QuizPoints.java, src/main/webapp/quizFunctions.js
=> Minor Changes (I am not creative enough to diversify this pr names!)

src/main/java/com/google/sps/servlets/GetUserInformation.java, src/main/java/com/google/sps/servlets/PopulateGamePage.java, src/main/webapp/gameBoard.html, src/main/webapp/gameFunctions.js
Code to populate the gameboard with the user's entity.
=> Populate the gameboard

pom.xml
=> forgot the dependency for manually translating to json

src/main/java/com/google/plantasy/utils/QuizTimingPropertiesUtils.java, src/test/java/com/google/plantasy/TimingPropertiesTest.java
changed the way I handled nulls in test cases; I got rid of try catch blocks in helper functions
=> Fix null handling in tests 

pom.xml, src/main/java/com/google/sps/servlets/startGameServlet.java, src/main/java/com/google/sps/utils/GameUtils.java, src/main/java/com/google/sps/utils/UserUtils.java, src/test/java/com/google/sps/GameUtilTest.java, src/test/java/com/google/sps/UserUtilTest.java
Remove null checks in game utils functions and some user utils functions and test for those functions throwing exceptions instead.
=> Remove null checks

src/main/webapp/gameBoard.html, src/main/webapp/gameFunctions.js, src/main/webapp/style.css
(look at deployed version for the updates)
=> style changes to gameboard

src/main/java/com/google/sps/AuthenticationFilter.java, src/main/webapp/web.xml
This is just the filter and web.xml. When it gets merged, it will break the website because logging in does not work yet
=> Filter and Web.xml For Authentication

src/main/java/com/google/plantasy/servlets/QuizPoints.java, src/main/java/com/google/plantasy/servlets/UserQuizStatusServlet.java, src/main/java/com/google/plantasy/utils/QuizTimingPropertiesUtils.java
The user's time is now compared to today's time. Also the code was fixed to properly give points to the person who took the quiz
=> Fixing the timing element

src/main/java/com/google/plantasy/servlets/LogoutServlet.java, src/main/java/com/google/plantasy/utils/User.java
Invalidates the user's session, deletes the session ID from the user entity, and removes the cookie that's tracking log in
=> Entire Logout Functionality

src/main/java/com/google/plantasy/utils/QuizTimingPropertiesUtils.java, src/test/java/com/google/plantasy/TimingPropertiesTest.java
Add three test for the new userHasTakenQuiz() function. Also got rid of instantiating QuizTimingProperties since all the methods I call are static. Some functions may look different because they got reverted back to old changes so I added them back in here
=> Fixingtests

pom.xml, src/main/java/com/google/plantasy/filter/AuthenticationFilter.java, src/main/java/com/google/plantasy/servlets/GameQuizStatusServlet.java, src/main/java/com/google/plantasy/servlets/GetUserInformation.java, src/main/java/com/google/plantasy/servlets/LoginServlet.java, src/main/java/com/google/plantasy/utils/PasswordReaderUtils.java, src/main/webapp/loggedin/gameFunctions.js
=> Finishing Touches (woop woop)
